openapi: 3.0.0
info:
  title: "Ecocycle API - DSSD 2024 (Grupo 2)"
  description: "Documentación de la API de Ecocycle usando Swagger"
  version: "1.0.0"
  contact:
    name: "Guadalupe Evequoz, Joaquín Spinelli, Pablo Terrone"
paths:
  /api/users/login:
    post:
      summary: Iniciar sesión
      description: Obtener token JWT para acceder a la aplicación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: jspinelli
                password:
                  type: string
                  example: jspinelli
      responses:
        200:
          description: Sesión iniciada con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  token:
                    type: string
                    example: <JWT>
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          email:
                            type: string
                            format: email
                            example: joaquin@ecocycle.com
                          dni:
                            type: integer
                            example: 12345678
                          username:
                            type: string
                            example: jspinelli
                          fullName:
                            type: string
                            example: Joaquín Spinelli
                          role:
                            type: string
                            example: recolector
        400:
          description: Inicio de sesión fallido (campos obligatorios no completados)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: Must provide username and password
        401:
          description: Inicio de sesión fallido (credenciales inválidas)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type: string
                    example: Invalid credentials
  /api/orders:
    get:
      summary: Obtener todas las órdenes disponibles
      description: Devuelve todas las órdenes con el estado "created".
      responses:
        200:
          description: Lista de órdenes obtenida con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      results:
                        type: integer
                        example: 1
                      orders:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            status:
                              type: string
                              example: "created"
                            depositId:
                              type: integer
                              example: null
                            createdAt:
                              type: string
                              example: "2024-10-11T19:28:24.851Z"
                            completedAt:
                              type: string
                              example: null
                            observations:
                              type: string
                              example: "Entrega urgente"
    post:
      summary: Crear una nueva orden
      description: Crea una nueva orden con observaciones y materiales.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                observations:
                  type: string
                  example: "Necesario antes del viernes"
                materials:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      amount:
                        type: integer
                        example: 5
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      amount:
                        type: integer
                        example: 10
      responses:
        201:
          description: Orden creada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      order:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          status:
                            type: string
                            example: "created"
                          createdAt:
                            type: string
                            example: "2024-10-12T18:08:22.473Z"
                          completedAt:
                            type: string
                            example: null
                          depopsitId:
                            type: integer
                            example: null
                          observations:
                            type: string
                            example: "Necesario antes del viernes"
        400:
          description: Error en la solicitud (campos obligatorios faltantes o inválidos)
  /api/orders/{id}:
    get:
      summary: Obtener una orden por ID
      description: Devuelve la orden con el ID especificado.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID de la orden
      responses:
        200:
          description: Orden obtenida con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      order:
                        type: object
                        properties:
                          id:
                              type: integer
                              example: 1
                          status:
                              type: string
                              example: "created"
                          depositId:
                              type: integer
                              example: null
                          createdAt:
                              type: string
                              example: "2024-10-11T19:28:24.851Z"
                          completedAt:
                              type: string
                              example: null
                          observations:
                              type: string
                              example: "Entrega urgente"
                          materials:
                            type: array
                            items:
                              type: object
                              properties:
                                    id:
                                      type: integer
                                      example: 1
                                    amount:
                                      type: integer
                                      example: 10
                                    materialId:
                                      type: integer
                                      example: 2
                                    orderId:
                                      type: integer
                                      example: 1
                                    material:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          id:
                                            type: integer
                                            example: 2
                                          name:
                                            type: string
                                            example: "Tela"
                                          unit:
                                            type: string
                                            example: "Unidades"
                                          pricePerUnit:
                                            type: double
                                            example: 20
        404:
          description: Orden no encontrada